eureka:
  instance:
    hostname: ${serviceRegistry:localhost}
  client:
    register-with-eureka: false
    fetch-registry: false
server:
  port: 8761

allowed:
  origins: "http://localhost:8080,http://192.168.0.8:8080,http://192.168.1.8:8080"